### ISSUE TITLE
Solid Fueled Steam Boiler doesn't output buckets

### ISSUE THREAD

**Issue by MatsonKey** [railcraft-reborn/railcraft#195] opened 2024-04-07 18:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Solid Fueled Steam Boiler takes buckets of fuel, such as lava buckets, as input, but it is impossible to take them out. 

### Railcraft Reborn version

1.1.0

### NeoForge/Forge version

47.2.6

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place lava bucket in Solid Fueled Steam Boiler
2. Try to take the empty bucket out through any method

### Expected behavior

Old Railcraft always sent empty buckets to the fluid output slot so they could be taken out.

### Logs & Environment

```Shell
I have tried hoppers, Create funnels and chutes, EnderIO conduits and GregTech pipes.
```

### Screenshots & Video

![image](https://github.com/railcraft-reborn/railcraft/assets/63819702/479570aa-9b6e-4112-8241-9fb7a7706219)

**Comment by Edivad99** [comment] 2024-04-08 19:11
Try 1.1.1 version the bug should be fixed

**Comment by DinnerBeef** [comment] 2024-09-30 20:12
Seems like this bug is still happening on version 1.2.2

**Comment by Edivad99** [comment] 2024-10-05 10:05
@DinnerBeef I can't reproduce it, if I put a bucket of lava, once empty I can take it from the inventory

**Closed as not planned by Edivad99** 2024-10-05 10:05 UTC
Labels: bug

**Comment by DinnerBeef** [comment] 2024-10-05 19:19
Sorry should of mention. I can't take it out with hoppers or any item dusts
