### ISSUE TITLE
Crash When Loco Hits Cactus

### ISSUE THREAD

**Issue by JSDrums1** [railcraft-reborn/railcraft#97] opened 2023-08-23 09:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Attempting to make an automatic train dispenser/return system. Using a cactus to break a train (as you usually would with a cart) and by sucked through a hopper etc, when the loco breaks, the game crashes (or if on a server the server crashes).

### Configuration

```Markdown
- Mod version: 1.0.3
- NeoForge/Forge version: Forge 47.1.0
- Minecraft version:1.20.1
- Are you playing on a server?: Both server and local test game has same problem
```

### To Reproduce

1. Place strip of track
2. place sand with cactus at the end
3. send a loco down the track to hit the cactus

### Expected behavior

loco hits cactus, breaking the loco and leaving drops behind, loco able to be sucked in by hopper beneath, game continues to run

### Logs & Environment

```Shell
2 x logs
1: Crash log from server : https://pastebin.com/emwTNTxa
2: Smaller log from local test game : The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: MinecartExtension missing on CreativeLocomotive['Creative Locomotive'/67, l='ServerLevel[New World]', x=68.57, y=-60.00, z=89.50, removed=KILLED]
```

### Screenshots & Video

![2023-08-23_10 28 28](https://github.com/railcraft-reborn/railcraft/assets/134440015/64cf80d6-0aac-499f-90b2-1d7ad6311bf8)

**Comment by Edivad99** [comment] 2023-08-23 09:57
Duplicate of #87

**Closed as completed by Edivad99** 2023-08-23 09:57 UTC
Labels: duplicate
